const DEFAULT_ROWS = 12;
const DEFAULT_COLS = 20;
const STORE_KEY = "artcii-box-studio-projects";
const LAST_KEY = "artcii-box-studio-last";
const U = 1;
const R = 2;
const D = 4;
const L = 8;

const els = {
  projectName: document.querySelector("#projectName"),
  projectList: document.querySelector("#projectList"),
  saveProject: document.querySelector("#saveProject"),
  newProject: document.querySelector("#newProject"),
  layers: document.querySelector("#layers"),
  deleteLayer: document.querySelector("#deleteLayer"),
  addLayer: document.querySelector("#addLayer"),
  exportToggle: document.querySelector("#exportToggle"),
  exportMenu: document.querySelector("#exportMenu"),
  copyEcho: document.querySelector("#copyEcho"),
  copyText: document.querySelector("#copyText"),
  downloadImage: document.querySelector("#downloadImage"),
  toolDraw: document.querySelector("#toolDraw"),
  toolErase: document.querySelector("#toolErase"),
  undo: document.querySelector("#undo"),
  redo: document.querySelector("#redo"),
  stage: document.querySelector("#stage"),
  artFrame: document.querySelector("#artFrame"),
  grid: document.querySelector("#grid"),
  rowsInput: document.querySelector("#rowsInput"),
  colsInput: document.querySelector("#colsInput"),
  brushPreview: document.querySelector("#brushPreview"),
  brushInput: document.querySelector("#brushInput"),
  nerdFont: document.querySelector("#nerdFont"),
  emojiToggle: document.querySelector("#emojiToggle"),
  emojiPanel: document.querySelector("#emojiPanel"),
  specialChar: document.querySelector("#specialChar"),
  specialPanel: document.querySelector("#specialPanel"),
  styleCycle: document.querySelector("#styleCycle"),
  sideUp: document.querySelector("#sideUp"),
  sideRight: document.querySelector("#sideRight"),
  sideDown: document.querySelector("#sideDown"),
  sideLeft: document.querySelector("#sideLeft"),
  sideCenter: document.querySelector("#sideCenter"),
  fgColors: document.querySelector("#fgColors"),
  bgColors: document.querySelector("#bgColors"),
  toast: document.querySelector("#toast"),
};

const glyphs = {
  single: {
    [0]: " ",
    [U]: "╵",
    [R]: "╶",
    [D]: "╷",
    [L]: "╴",
    [U | D]: "│",
    [L | R]: "─",
    [D | R]: "┌",
    [D | L]: "┐",
    [U | R]: "└",
    [U | L]: "┘",
    [U | D | R]: "├",
    [U | D | L]: "┤",
    [D | L | R]: "┬",
    [U | L | R]: "┴",
    [U | R | D | L]: "┼",
  },
  heavy: {
    [0]: " ",
    [U]: "╹",
    [R]: "╺",
    [D]: "╻",
    [L]: "╸",
    [U | D]: "┃",
    [L | R]: "━",
    [D | R]: "┏",
    [D | L]: "┓",
    [U | R]: "┗",
    [U | L]: "┛",
    [U | D | R]: "┣",
    [U | D | L]: "┫",
    [D | L | R]: "┳",
    [U | L | R]: "┻",
    [U | R | D | L]: "╋",
  },
  rounded: {
    [0]: " ",
    [U]: "╵",
    [R]: "╶",
    [D]: "╷",
    [L]: "╴",
    [U | D]: "│",
    [L | R]: "─",
    [D | R]: "╭",
    [D | L]: "╮",
    [U | R]: "╰",
    [U | L]: "╯",
    [U | D | R]: "├",
    [U | D | L]: "┤",
